# Generated by Django 3.0.6 on 2020-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='vendedor',
            field=models.CharField(default='Tienda Ferme', max_length=200),
        ),
    ]
