# Generated by Django 3.0.6 on 2020-06-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200606_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fact',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_factura', models.CharField(max_length=200)),
                ('vendedor', models.CharField(default='Tienda Ferme', max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order')),
            ],
        ),
    ]
