# Generated by Django 3.0.6 on 2020-06-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_ordencompra_ordenitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='date_ordered',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='empleado',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='detalle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Profile'),
        ),
        migrations.DeleteModel(
            name='OrdenItems',
        ),
    ]
