# Generated by Django 2.2.13 on 2020-06-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200629_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_exp',
            field=models.CharField(blank=True, default=False, max_length=8, null=True),
        ),
    ]
