# Generated by Django 3.0.6 on 2020-07-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200629_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_exp',
            field=models.CharField(blank=True, default='31/12/2020', max_length=10, null=True),
        ),
    ]
