# Generated by Django 3.0.6 on 2020-07-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200710_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En espera', max_length=50),
        ),
    ]
